project:
  name: quickstart-biotech-blueprint
  owner: quickstart-eng@amazon.com
  shorten_stack_name: true
  package_lambda: false
  s3_regional_buckets: true
  regions:
    - us-east-1
    - us-west-2
    - eu-west-1
tests:
  quickstart-biotech-blueprintt1:
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-biotech-blueprint/
      pAvailabilityZones: $[taskcat_genaz_2]
      pInternalDnsSecondLevelDomain: corp
      pInternalDnsTLDDomain: com
      pKeyPairName: paulu-hclscollab-taskcat
      pManagementVPCCidrAandBBlock: "10.132"
      pNotifyEmail: distlist@example.org
      pPreclinicalVPCCidrAandBBlock: "10.131"
      pSupportConfig: "No"
      pTargetNetworkCidr: 0.0.0.0/0
    regions:
      - us-east-1
      - us-west-2
      - eu-west-1 
    template: templates/biotech-blueprint-master.template.yaml
